<?php
    $viewTitle = isset($this->viewTitle) ? $this->viewTitle : "";
    $viewDescription = isset($this->viewDescription) ? $this->viewDescription : "";
    $viewImage = isset($this->viewImage) ? $this->viewImage : "";
    $viewKeywords = isset($this->viewKeywords) ? $this->viewKeywords : "";
?>
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" />
    <meta name="image" content="<?php echo $viewImage; ?>">
    <meta name="keywords" content="<?php echo $viewKeywords; ?>" />
    <meta name="description" content="<?php echo $viewDescription ?>" />
    <title><?php echo $viewTitle ?></title>
</head>
<body>
    <?php 
        $this->render(); 
    ?>
</body>
</html>
